# Generated by Django 5.2 on 2025-05-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0004_bus_via_times_train_via_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='via_times',
            field=models.TimeField(default='N/A', help_text='Comma-separated times matching each via stop (e.g., 09:30,10:00,10:30)'),
        ),
    ]
