# Generated by Django 5.2 on 2025-05-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0005_alter_bus_via_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='via_times',
            field=models.TextField(default='N/A', help_text='Comma-separated times matching each via stop (e.g., 09:30,10:00,10:30)'),
        ),
    ]
