# Generated by Django 5.2 on 2025-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0006_alter_bus_via_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Unique identifier for the bus.', max_length=50, unique=True)),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Sleeper', 'Sleeper'), ('Ordinary', 'Ordinary'), ('Express', 'Express')], default='Ordinary', help_text='Type of bus (e.g., AC, Non-AC, Sleeper).', max_length=50)),
                ('start_point', models.CharField(help_text='Starting location of the bus route.', max_length=100)),
                ('destination_point', models.CharField(help_text='Destination location of the bus route.', max_length=100)),
                ('arrival_time', models.DateTimeField(help_text='Scheduled arrival time at the start point.')),
                ('departure_time', models.DateTimeField(help_text='Scheduled departure time from the start point.')),
                ('reaching_time', models.DateTimeField(help_text='Scheduled reaching time at the destination point.')),
                ('via_stops', models.JSONField(blank=True, default=list, help_text="List of intermediate stops with their approximate times (e.g., [{'stop': 'City A', 'time': 'HH:MM AM/PM'}]).")),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Unique identifier for the train.', max_length=50, unique=True)),
                ('train_type', models.CharField(choices=[('Express', 'Express'), ('Local', 'Local'), ('Passenger', 'Passenger'), ('Shatabdi', 'Shatabdi'), ('Rajdhani', 'Rajdhani')], default='Express', help_text='Type of train (e.g., Express, Local, Passenger).', max_length=50)),
                ('start_point', models.CharField(help_text='Starting station of the train route.', max_length=100)),
                ('destination_point', models.CharField(help_text='Destination station of the train route.', max_length=100)),
                ('arrival_time', models.DateTimeField(help_text='Scheduled arrival time at the start station.')),
                ('departure_time', models.DateTimeField(help_text='Scheduled departure time from the start station.')),
                ('reaching_time', models.DateTimeField(help_text='Scheduled reaching time at the destination station.')),
                ('via_stops', models.JSONField(blank=True, default=list, help_text="List of intermediate stations with their approximate times (e.g., [{'stop': 'Station A', 'time': 'HH:MM AM/PM'}]).")),
                ('days_of_service', models.CharField(blank=True, default='', help_text="Comma-separated list of days the train operates (e.g., 'MON,WED,FRI').", max_length=500)),
            ],
            options={
                'verbose_name': 'Train Route',
                'verbose_name_plural': 'Train Routes',
                'ordering': ['departure_time'],
            },
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
