# Generated by Django 5.2 on 2025-05-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0007_busroute_trainroute_delete_bus_delete_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='number',
            field=models.CharField(help_text='KA21Fxyza', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='via_stops',
            field=models.JSONField(blank=True, default=list, help_text=" [Type like this {'stop': 'City A', 'time': 'HH:MM AM/PM'}]."),
        ),
        migrations.AlterField(
            model_name='trainroute',
            name='train_type',
            field=models.CharField(choices=[('Express', 'Express'), ('Local', 'Local'), ('Passenger', 'Passenger')], default='Express', help_text='Type of train (e.g., Express, Local, Passenger).', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainroute',
            name='via_stops',
            field=models.JSONField(blank=True, default=list, help_text="List of intermediate stations (Type like this()This is for Bhavish B[{'stop': 'Station A', 'time': 'HH:MM AM/PM'}])."),
        ),
    ]
